cache: bundler
sudo: false
language: ruby

addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3

matrix:
  include:
    - rvm: 2.4.1
      gemfile: gemfiles/activerecord_5_0.gemfile
      env: "DB=sqlite"
    - rvm: 2.4.1
      gemfile: gemfiles/activerecord_5_0.gemfile
      env: "DB=postgresql"
    - rvm: 2.4.1
      gemfile: gemfiles/activerecord_5_0.gemfile
      env: "DB=mysql"
    - rvm: 2.3.4
      gemfile: gemfiles/activerecord_4_2.gemfile
      env: "DB=postgresql"
    - rvm: 2.3.4
      gemfile: gemfiles/activerecord_4_2.gemfile
      env: "DB=sqlite"
    # Please note that gem can't be tested against MySQL on ActiveRecord 4.2 (Dump and restore test doesn't work)!
